[build]
  command = "npm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Handle SPA routing - redirect all routes to index.html
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Handle favicon and other static assets
[[redirects]]
  from = "/favicon.ico"
  to = "/favicon.ico"
  status = 200

# Handle CSS and JS assets
[[redirects]]
  from = "/assets/*"
  to = "/assets/:splat"
  status = 200

# Handle images and other static files
[[redirects]]
  from = "/*.png"
  to = "/:splat"
  status = 200

[[redirects]]
  from = "/*.mp4"
  to = "/:splat"
  status = 200

# Add headers for MP4 files
[[headers]]
  for = "/*.mp4"
  [headers.values]
    Content-Type = "video/mp4"
    Cache-Control = "public, max-age=31536000"
